version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - discovery.type=single-node
    #   ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200:9200
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
  kibana:
    # image: docker.elastic.co/kibana/kibana:6.2.2
    build: 
      context: kibana/
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes: 
      - ./kibana/plugins/logtrail.json:/usr/share/kibana/plugins/logtrail/logtrail.json
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    networks: 
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "9600:9600"
    networks: 
      - elk
    depends_on: 
      - elasticsearch
      - redis
    links:
      - redis
      - elasticsearch

  opg:
    image: opg
    ports:
      - "80:80"
      - "8080:8080"


networks: 
  elk: